import { inter } from "@/lib/styles/fonts";
import type { Metadata } from "next";
import { ReactNode } from "react";
import "@/lib/styles/globals.css";

export const metadata: Metadata = {
  title: "Acme Financial Dashboard",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>{children}</body>
    </html>
  );
}
